# Generated by Django 3.1.4 on 2020-12-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='content',
            new_name='abstract',
        ),
    ]
